# Generated by Django 3.2.5 on 2021-07-21 15:27

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import gnosis.eth.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('cf', models.CharField(max_length=16, unique=True)),
                ('region', models.CharField(choices=[('ABRUZZO', 'Abr'), ('BASILICATA', 'Bas'), ('CALABRIA', 'Cal'), ('CAMPANIA', 'Cam'), ('EMILIA-ROMAGNA', 'Emr'), ('FRIULI-VENEZIA-GIULIA', 'Fvg'), ('LAZIO', 'Laz'), ('MARCHE', 'Mar'), ('MOLISE', 'Mol'), ('PROVINCIA-AUTONOMA-BOLZANO', 'Pab'), ('PROVINCIA-AUTONOMA-TRENTO', 'Pat'), ('PIEMONTE', 'Pmt'), ('PUGLIA', 'Pug'), ('SARDEGNA', 'Sar'), ('SICILIA', 'Sic'), ('TOSCANA', 'Tos'), ('UMBRIA', 'Umb'), ('VALLE-D-AOSTA', 'Vda'), ('VENETO', 'Ven')], max_length=30)),
            ],
            options={
                'verbose_name': 'Citizen',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PublicAuthority',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaOperator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('operator_code', models.CharField(max_length=10, unique=True)),
                ('bc_address', gnosis.eth.django.models.EthereumAddressField()),
                ('bc_secret_key', models.CharField(max_length=200)),
                ('public_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.publicauthority')),
            ],
            options={
                'verbose_name': 'Pa Operator',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
