# Generated by Django 3.2.5 on 2021-07-21 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gnosis.eth.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersionTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_address', gnosis.eth.django.models.EthereumAddressField()),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_address', gnosis.eth.django.models.HexField(max_length=500)),
                ('hash_fingerprint', models.CharField(max_length=256)),
                ('download_url', models.URLField()),
                ('document_version', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='version_transaction', to='document.documentversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentSC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_address', gnosis.eth.django.models.EthereumAddressField()),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_address', gnosis.eth.django.models.EthereumAddressField(unique=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='document_sc', to='document.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
